package com.example.echo_wave.utils;

import java.util.Arrays;
import java.util.List;

public class ArtistData {
    public static List<String> getArtists() {
        return Arrays.asList(
                // ========== NIGERIAN GOSPEL ARTISTS ==========
                "Sinach",
                "Nathaniel Bassey",
                "Mercy Chinwo",
                "Eben",
                "Frank Edwards",
                "Tope Alabi",
                "Tim Godfrey",
                "Judikay",
                "Dunsin Oyekan",
                "Ada Ehi",
                "Lawrence Oyor",
                "EeZee Tee",
                "Samsong",
                "Mike Aremu",
                "Panam Percy Paul",
                "Steve Crown",
                "Obiwon",
                "Henrisoul",
                "Prospa Ochimana",
                "Moses Bliss",
                "Ebuka Songs",
                "Sunmisola Agbebi",
                "Victory",
                "GUC",
                "Festizie",
                "Onos Ariyo",
                "Nosa",
                "Buchi",
                "Sammie Okposo",
                "Lara George",
                "Asu Ekiye",

                // ========== NIGERIAN AFROBEAT/AFROPOP ARTISTS ==========
                "Burna Boy",
                "Wizkid",
                "Davido",
                "Rema",
                "Asake",
                "Omah Lay",
                "CKay",
                "Fireboy DML",
                "Joeboy",
                "Ayra Starr",
                "Tems",
                "Olamide",
                "Phyno",
                "Zlatan",
                "Mayorkun",
                "Kizz Daniel",
                "Tekno",
                "Patoranking",
                "Ruger",
                "BNXN",
                "Sarz",
                "Ladipoe",
                "Falz",
                "Simi",
                "Tiwa Savage",
                "Yemi Alade",
                "Niniola",
                "Seyi Shay",
                "Chidinma",
                "Wande Coal",
                "D'Prince",
                "Skiibii",
                "Bella Shmurda",
                "Mohbad",
                "Crayon",
                "Magixx",
                "Young Jonn",
                "Shallipopi",
                "Odumodublvck",
                "Seyi Vibez",
                "Victony",
                "Boj",
                "Oxlade",
                "Chike",
                "Johnny Drille",
                "Ric Hassani",
                "Show Dem Camp",
                "A-Q",
                "Blaqbonez",
                "Psycho YP",
                "Cheque",
                "Peruzzi",
                "Lyta",
                "Zinoleesky",
                "Qdot",
                "Portable",
                "Oritse Femi",
                "Small Doctor",
                "Dice Ailes",
                "Runtown",
                "Harrysong",
                "Kcee",
                "Flavour",
                "Zoro",
                "Humblesmith",
                "Lil Kesh",
                "Naira Marley",
                "Brodda Shaggi",

                // ========== NIGERIAN LEGENDS ==========
                "Fela Kuti",
                "Femi Kuti",
                "Seun Kuti",
                "King Sunny Ade",
                "Ebeneezer Obey",
                "Victor Olaiya",
                "Oliver De Coque",
                "Osita Osadebe",
                "Bright Chimezie",
                "Rex Lawson",
                "Onikeke",
                "Sir Shina Peters",
                "Pasuma",
                "Saheed Osupa",
                "Wasiu Ayinde",

                // ========== NIGERIAN HIP HOP ==========
                "M.I Abaga",
                "Vector",
                "Ice Prince",
                "Jesse Jagz",
                "Reminisce",
                "Illbliss",
                "Naeto C",
                "Mode 9",
                "Erigga",
                "Ycee",

                // ========== NIGERIAN R&B ==========
                "Banky W",
                "Waje",
                "Omawumi",
                "Timi Dakolo",
                "Praiz",
                "Iyanya",
                "Dr Sid",
                "Darey",
                "Ego",
                "Niyola",

// ========== ZAMBIAN ARTISTS (COMPLETE LIST) ==========
// LEGENDARY/ESTABLISHED ARTISTS
                "Chile One",
                "Yo Maps",
                "Y Celeb",
                "Slapdee",
                "Chef 187",
                "Macky 2",
                "Roberto",
                "B Flow",
                "Jemax",
                "Jay Rox",
                "Cleo Ice Queen",
                "Pilato",
                "Dandy Crazy",
                "K'Millian",
                "T-Sean",
                "Chanda Mbao",
                "Bobby East",
                "Jae Cash",
                "Dizmo",
                "Mag44",
                "Jorzi",
                "Xaven",
                "Ruff Kid",
                "Aqualaskin",
                "Zone Fam",
                "Elisha Long",
                "Rich Bizzy",
                "Mampi",
                "Abel Chungu",
                "James Sakala",
                "Mwanjé",
                "Natasha Chansa",
                "Lulu",
                "Mr. Stash",
                "Bwembya",
                "Blood Kid",
                "B-More",
                "Tim",
                "Petra",
                "Muzo",
                "Chikito",
                "Thugga",
                "Shyman",
                "Stevo",
                "Willz",
                "Mumba Yachi",
                "Jeto",
                "Jay B",
                "Krytic",
                "Cargo",
                "Zorro",
                "Kekero",
                "Jaro Local",
                "Mr. Mwale",
                "T-Bwoy",
                "Billion",
                "Chikumbi",
                "Maiko Zulu",
                "Evans Kaunda",
                "Benson Mulenga",
                "Alfred Chirwa",
                "Patience",
                "Emmie Mwape",
                "Shamiso",
                "Zesty",
                "Chilu Lemba",
                "Peter Mwanza",
                "Exile",
                "Rion Kenani",
                "Neo",
                "Tommy Dee",
                "Teejay",
                "TK",
                "Small B",
                "Jazzy",
                "King Dandy",
                "Natasha Mwansa",
                "Lulu Haangala",
                "Lulu Fumba",
                "Neo Ntobeko",
                "TK Shotta",
                "Small Bill",
                "Jazzy Boy",
                "Dr. Exile",
                "Kmillian",
                "Rebel",
                "Rion",
                "Tommy D",
                "Danny",
                "Tejay",
                "Kopala",
                "Kopala Swag",
                "Mampi Mwila",
                "Benson Mwila",
                "Chanda Chileshe",
                "Kasonde Banda",
                "Banda Phiri",
                "Mwila Musonda",
                "Mulenga Chanda",
                "Shadrick",
                "Shadreck",
                "Chanda",
                "Bwalya",
                "Mumba",
                "Lungu",
                "Philemon",
                "Chisanga",
                "Mulenga",
                "Musonda",
                "Mukuka",
                "Mbewe",
                "Chishala",
                "Chisenga",
                "Nyambe",
                "Mwansa",
                "Ngoma",
                "Nyoni",
                "Sichinga",
                "Sikazwe",
                "Silwimba",
                "Simwanza",
                "Simwawa",
                "Simwinga",
                "Simwaka",
                "Singogo",
                "Sinkala",
                "Siwale",
                "Tembo",
                "Thole",
                "Zimba",
                "Banda",
                "Phiri",
                "Chanda",
                "Kunda",
                "Mwanza",
                "Mwape",
                "Chibesa",
                "Chileshe",
                "Chilufya",
                "Chiluba",
                "Chimfwembe",
                "Chinkuli",
                "Chisala",
                "Chisanga",
                "Chita",
                "Chola",
                "Chomba",
                "Chongo",
                "Choolwe",
                "Chota",
                "Chulu",
                "Chungu",
                "Daka",
                "Fumpa",
                "Habasimbi",
                "Hamalala",
                "Hantuba",
                "Jere",
                "Kalaba",
                "Kalunga",
                "Kalungu",
                "Kalusha",
                "Kambole",
                "Kampamba",
                "Kamwendo",
                "Kangwa",
                "Kaniki",
                "Kapembwa",
                "Kapilimbi",
                "Kapisha",
                "Kaputo",
                "Kasanda",
                "Kaseba",
                "Kasengele",
                "Kashimoto",
                "Kasoma",
                "Katampi",
                "Katema",
                "Katongo",
                "Kawanga",
                "Kayombo",
                "Kazembe",
                "Kazunga",
                "Kunda",
                "Lengo",
                "Lwamba",
                "Lwando",
                "Lwandamina",
                "Mabenga",
                "Mabwe",
                "Machila",
                "Mafuta",
                "Makanika",
                "Makesa",
                "Malama",
                "Mambwe",
                "Manda",
                "Mangani",
                "Mansoor",
                "Mansour",
                "Mapani",
                "Maseka",
                "Masiye",
                "Masoja",
                "Mataka",
                "Matambo",
                "Matipa",
                "Mawere",
                "Mazuba",
                "Mazunda",
                "Mazunga",
                "Mbao",
                "Mbewe",
                "Mboozi",
                "Mbulu",
                "Mbuta",
                "Mchenga",
                "Mfula",
                "Mfuni",
                "Mhango",
                "Mhone",
                "Mibenge",
                "Miche",
                "Mikabe",
                "Mikala",
                "Mikonde",
                "Mikulika",
                "Milambo",
                "Milingo",
                "Milimo",
                "Milubi",
                "Mimbi",
                "Mimie",
                "Mimosa",
                "Minafu",
                "Minda",
                "Mine",
                "Misheck",
                "Misika",
                "Misozi",
                "Mitima",
                "Mitondo",
                "Miyoba",
                "Miyoba",
                "Mkandawire",
                "Mkandawire",
                "Mkandawire",
                "Mkisi",
                "Mkoma",
                "Mkono",
                "Mkota",
                "Mkushi",
                "Mkusi",
                "Mkweu",
                "Mkweu",
                "Mlenga",
                "Mlengi",
                "Mlima",
                "Mlimo",
                "Mlongoti",
                "Mluwazi",
                "Mma",
                "Mmalume",
                "Mmayi",
                "Mmbangwa",
                "Mmbeti",
                "Mmbongo",
                "Mmbulwa",
                "Mmbulwa",
                "Mmbulu",
                "Mmbundu",
                "Mmbundu",
                "Mmbusi",
                "Mmbwa",
                "Mmbwe",
                "Mmbwe",
                "Mmbwembe",
                "Mmbwembe",
                "Mmbwewe",
                "Mmbwewe",
                "Mmbwile",
                "Mmbwile",
                "Mmbwili",
                "Mmbwili",
                "Mmbwima",
                "Mmbwima",
                "Mmbwimba",
                "Mmbwimba",
                "Mmbwindi",
                "Mmbwindi",
                "Mmbwipa",
                "Mmbwipa",
                "Mmbwisa",
                "Mmbwisa",
                "Mmbwita",
                "Mmbwita",
                "Mmbwiti",
                "Mmbwiti",
                "Mmbwiza",
                "Mmbwiza",

                // ========== INTERNATIONAL GOSPEL ==========
                "Kirk Franklin",
                "Donnie McClurkin",
                "Marvin Sapp",
                "Tasha Cobbs",
                "CeCe Winans",
                "Travis Greene",
                "Tye Tribbett",
                "William McDowell",
                "Hillsong United",
                "Hillsong Worship",
                "Elevation Worship",
                "Bethel Music",
                "Maverick City Music",
                "Chris Tomlin",
                "Lauren Daigle",
                "Kari Jobe",
                "Israel Houghton",
                "Todd Dulaney",
                "Jekalyn Carr",
                "Tamela Mann",

                // ========== INTERNATIONAL AFROBEAT ==========
                "Shatta Wale",
                "Stonebwoy",
                "King Promise",
                "Kuami Eugene",
                "Mr Eazi",
                "J Hus",
                "Skepta",
                "Kojo Funds",
                "NSG",

                // ========== SOUTH AFRICAN AMAPIANO ==========
                "Kabza De Small",
                "DJ Maphorisa",
                "Focalistic",
                "Mellow & Sleazy",
                "Major League DJz",
                "Vigro Deep",
                "DBN Gogo",

                // ========== POP ARTISTS ==========
                "Taylor Swift",
                "Ed Sheeran",
                "Ariana Grande",
                "Justin Bieber",
                "Shawn Mendes",
                "Dua Lipa",
                "Billie Eilish",
                "Bruno Mars",
                "Katy Perry",
                "Lady Gaga",
                "The Weeknd",
                "Rihanna",
                "Beyoncé",
                "Adele",
                "Sam Smith",
                "Camila Cabello",
                "Charlie Puth",
                "Selena Gomez",
                "Demi Lovato",
                "Miley Cyrus",
                "Sia",
                "Lana Del Rey",
                "Halsey",
                "Lorde",

                // ========== ROCK ARTISTS ==========
                "Imagine Dragons",
                "Coldplay",
                "Maroon 5",
                "OneRepublic",
                "The Beatles",
                "Queen",
                "Linkin Park",
                "Green Day",
                "Foo Fighters",
                "Red Hot Chili Peppers",
                "Arctic Monkeys",
                "The Killers",
                "Muse",
                "The Rolling Stones",
                "Nirvana",
                "Guns N' Roses",
                "Metallica",
                "AC/DC",
                "Bon Jovi",
                "U2",
                "Florence + The Machine",
                "Vampire Weekend",
                "The 1975",
                "Twenty One Pilots",
                "Panic! At The Disco",
                "Fall Out Boy",

                // ========== HIP HOP/RAP ==========
                "Drake",
                "Kendrick Lamar",
                "Eminem",
                "Jay-Z",
                "Kanye West",
                "Travis Scott",
                "Post Malone",
                "J. Cole",
                "Nicki Minaj",
                "Cardi B",
                "Future",
                "Lil Wayne",
                "Migos",
                "21 Savage",
                "Lil Baby",
                "DaBaby",
                "Megan Thee Stallion",
                "Doja Cat",
                "Tyler The Creator",
                "A$AP Rocky",

                // ========== R&B/SOUL ==========
                "Frank Ocean",
                "SZA",
                "H.E.R.",
                "Daniel Caesar",
                "Jhené Aiko",
                "Khalid",
                "Ella Mai",
                "Chris Brown",
                "Usher",
                "Ne-Yo",
                "John Legend",
                "Alicia Keys",
                "Trey Songz",

                // ========== LATIN ==========
                "Bad Bunny",
                "J Balvin",
                "Daddy Yankee",
                "Ozuna",
                "Maluma",
                "Karol G",
                "Shakira",
                "Ricky Martin",
                "Enrique Iglesias",
                "Luis Fonsi",

                // ========== COUNTRY ==========
                "Luke Combs",
                "Morgan Wallen",
                "Blake Shelton",
                "Kane Brown",
                "Chris Stapleton",
                "Carrie Underwood",
                "Miranda Lambert",
                "Kacey Musgraves",
                "Maren Morris",
                "Thomas Rhett",

                // ========== ELECTRONIC/DANCE ==========
                "Calvin Harris",
                "David Guetta",
                "The Chainsmokers",
                "Marshmello",
                "Zedd",
                "Martin Garrix",
                "Alan Walker",
                "Skrillex",
                "Diplo",
                "Kygo",

                // ========== K-POP ==========
                "BTS",
                "BLACKPINK",
                "TWICE",
                "EXO",
                "Red Velvet",

                // ========== JAZZ/CLASSICAL ==========
                "Michael Bublé",
                "Frank Sinatra",
                "Norah Jones",
                "Ludovico Einaudi",
                "Yo-Yo Ma"
        );
    }
}